# -*- coding: utf-8 -*-
"""Log_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cd73pUv4d6_0J6jg3V_kmOvwFH48NB4D
"""

import os
import re
import warnings
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

from IPython.display import display

warnings.filterwarnings("ignore")

plt.style.use("default")
plt.rcParams["figure.figsize"] = (12, 6)
plt.rcParams["axes.titlesize"] = 14
plt.rcParams["axes.labelsize"] = 12

print("Libraries imported successfully.")

from google.colab import files

uploaded = files.upload()

file_path = next(iter(uploaded.keys()))
print(f"Uploaded file: {file_path}")

assert Path(file_path).exists(), "File not found after upload."

with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
    raw_lines = f.readlines()

print("Total raw lines:", len(raw_lines))
print("\nFirst 5 raw lines:\n")

for line in raw_lines[:5]:
    print(line.rstrip())

PATTERNS = [
    re.compile(
        r'^\[(?P<timestamp>[^\]]+)\]\s+\[(?P<level>[^\]]+)\]\s+\[client\s+(?P<client>[^\]]+)\]\s+(?P<message>.*)$'
    ),
    re.compile(
        r'^\[(?P<timestamp>[^\]]+)\]\s+\[(?P<level>[^\]]+)\]\s+(?P<message>.*)$'
    )
]

def parse_log_line(line: str):
    line = line.strip()

    if not line:
        return {
            "timestamp_raw": None,
            "log_level": None,
            "client": None,
            "message": None,
            "parsed_status": "blank"
        }

    for pattern in PATTERNS:
        match = pattern.match(line)
        if match:
            groups = match.groupdict()
            return {
                "timestamp_raw": groups.get("timestamp"),
                "log_level": groups.get("level"),
                "client": groups.get("client"),
                "message": groups.get("message").strip() if groups.get("message") else "",
                "parsed_status": "success"
            }

    return {
        "timestamp_raw": None,
        "log_level": None,
        "client": None,
        "message": line,
        "parsed_status": "unparsed"
    }

print("Parser function created successfully.")

records = []

for i, line in enumerate(raw_lines, start=1):
    row = parse_log_line(line)
    row["line_no"] = i
    row["raw_line"] = line.rstrip("\n")
    records.append(row)

df = pd.DataFrame(records)

print("Parsed rows:", len(df))
display(df.head(10))

df["timestamp_raw"] = df["timestamp_raw"].astype("string").str.strip()

df["timestamp"] = pd.to_datetime(
    df["timestamp_raw"],
    format="%a %b %d %H:%M:%S %Y",
    errors="coerce"
)

fallback_mask = df["timestamp"].isna() & df["timestamp_raw"].notna()
df.loc[fallback_mask, "timestamp"] = pd.to_datetime(
    df.loc[fallback_mask, "timestamp_raw"],
    errors="coerce"
)

df["log_level"] = df["log_level"].fillna("unknown").astype(str).str.lower()
df["client"] = df["client"].fillna("unknown").astype(str)
df["message"] = df["message"].fillna("").astype(str).str.strip()

df["parsed_status"] = df["parsed_status"].fillna("unparsed")
df["date"] = df["timestamp"].dt.date
df["hour"] = df["timestamp"].dt.hour
df["weekday"] = df["timestamp"].dt.day_name()

parsed_df = df[df["parsed_status"] == "success"].copy()
valid_df = parsed_df[parsed_df["timestamp"].notna()].copy()

print("After cleaning:")
print("Parsed rows:", len(parsed_df))
print("Valid timestamp rows:", len(valid_df))

display(df.head(10))

total_lines = len(df)
parsed_lines = len(parsed_df)
unparsed_lines = len(df[df["parsed_status"] == "unparsed"])
blank_lines = len(df[df["parsed_status"] == "blank"])

error_df = valid_df[valid_df["log_level"].str.contains("error", case=False, na=False)].copy()
error_lines = len(error_df)

parse_success_rate = (parsed_lines / total_lines * 100) if total_lines else 0

if not valid_df.empty:
    start_time = valid_df["timestamp"].min()
    end_time = valid_df["timestamp"].max()
    time_span = f"{start_time} to {end_time}"
else:
    time_span = "N/A"

summary = pd.DataFrame({
    "Metric": [
        "Total raw lines",
        "Parsed lines",
        "Unparsed lines",
        "Blank lines",
        "Parse success rate (%)",
        "Error lines",
        "Unique log levels",
        "Time span"
    ],
    "Value": [
        total_lines,
        parsed_lines,
        unparsed_lines,
        blank_lines,
        round(parse_success_rate, 2),
        error_lines,
        parsed_df["log_level"].nunique(),
        time_span
    ]
})

display(summary)

output_dir = Path("outputs")
output_dir.mkdir(exist_ok=True)

df.to_csv(output_dir / "parsed_logs.csv", index=False)
parsed_df.to_csv(output_dir / "parsed_only_logs.csv", index=False)
valid_df.to_csv(output_dir / "valid_timestamp_logs.csv", index=False)
summary.to_csv(output_dir / "summary_metrics.csv", index=False)

print(f"Files saved in: {output_dir.resolve()}")
print("Saved:")
print("- parsed_logs.csv")
print("- parsed_only_logs.csv")
print("- valid_timestamp_logs.csv")
print("- summary_metrics.csv")

level_counts = parsed_df["log_level"].value_counts()

if not level_counts.empty:
    ax = level_counts.plot(kind="bar")
    ax.set_title("Log Level Distribution")
    ax.set_xlabel("Log Level")
    ax.set_ylabel("Count")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.savefig(output_dir / "log_level_distribution.png", dpi=300, bbox_inches="tight")
    plt.show()
else:
    print("No log levels available for plotting.")

if not error_df.empty:
    daily_errors = error_df.groupby(error_df["timestamp"].dt.floor("D")).size().sort_index()

    if not daily_errors.empty:
        ax = daily_errors.plot(kind="line", marker="o")
        ax.set_title("Error Frequency Over Time (Daily)")
        ax.set_xlabel("Date")
        ax.set_ylabel("Error Count")
        plt.xticks(rotation=45, ha="right")
        plt.tight_layout()
        plt.savefig(output_dir / "error_frequency_daily.png", dpi=300, bbox_inches="tight")
        plt.show()
    else:
        print("No daily error data found.")
else:
    print("No error rows found for daily trend plot.")

if not error_df.empty:
    hourly_errors = error_df.groupby(error_df["timestamp"].dt.hour).size().sort_index()

    if not hourly_errors.empty:
        ax = hourly_errors.plot(kind="bar")
        ax.set_title("Error Frequency by Hour")
        ax.set_xlabel("Hour of Day")
        ax.set_ylabel("Error Count")
        plt.xticks(rotation=0)
        plt.tight_layout()
        plt.savefig(output_dir / "error_frequency_hourly.png", dpi=300, bbox_inches="tight")
        plt.show()
    else:
        print("No hourly error data found.")
else:
    print("No error rows found for hourly plot.")

def make_signature(msg):
    msg = re.sub(r"\s+", " ", str(msg)).strip()
    if not msg:
        return "unknown"

    for sep in [":", " - ", "|"]:
        if sep in msg:
            msg = msg.split(sep, 1)[0].strip()
            break

    return msg[:120]

if not error_df.empty:
    error_df = error_df.copy()
    error_df["error_signature"] = error_df["message"].apply(make_signature)

    top_errors = error_df["error_signature"].value_counts().head(10)

    if not top_errors.empty:
        ax = top_errors.plot(kind="bar")
        ax.set_title("Top 10 Repeated Error Messages")
        ax.set_xlabel("Error Message Signature")
        ax.set_ylabel("Count")
        plt.xticks(rotation=45, ha="right")
        plt.tight_layout()
        plt.savefig(output_dir / "top_error_messages.png", dpi=300, bbox_inches="tight")
        plt.show()
    else:
        print("No error signatures available.")
else:
    print("No error rows available for top error message plot.")

cluster_source = error_df["message"].dropna().astype(str)
cluster_source = cluster_source[cluster_source.str.strip() != ""]

unique_texts = pd.Series(cluster_source.unique())

if len(unique_texts) >= 3:
    max_messages = min(300, len(unique_texts))
    sample_texts = unique_texts.head(max_messages)

    n_clusters = min(5, len(sample_texts))

    if n_clusters >= 2:
        vectorizer = TfidfVectorizer(
            stop_words="english",
            max_features=1000,
            ngram_range=(1, 2)
        )

        X = vectorizer.fit_transform(sample_texts)

        if X.shape[1] > 0:
            km = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
            labels = km.fit_predict(X)

            cluster_df = pd.DataFrame({
                "error_message": sample_texts,
                "cluster": labels
            })

            display(cluster_df.head(10))

            terms = vectorizer.get_feature_names_out()
            order_centroids = km.cluster_centers_.argsort()[:, ::-1]

            print("\nTop terms per cluster:")
            for i in range(n_clusters):
                top_terms = [terms[ind] for ind in order_centroids[i, :5]]
                print(f"Cluster {i}: {', '.join(top_terms)}")

            cluster_df.to_csv(output_dir / "error_clusters.csv", index=False)
        else:
            print("TF-IDF produced no features.")
    else:
        print("Not enough unique messages for clustering.")
else:
    print("Not enough error messages for clustering.")

print("Cleaned DataFrame preview:")
display(df.head(10))

print("Summary metrics:")
display(summary)

print("Top repeated error messages:")
if not error_df.empty and "error_signature" in error_df.columns:
    display(error_df["error_signature"].value_counts().head(10).to_frame("count"))

